version: '3'
services:
  html:
    image: cenk1cenk2/node-fnm:latest
    environment:
      PACKAGE_MANAGER: pnpm
      DEFAULTS_LOGS: 'true'
      DEFAULTS_COMMAND: pnpm run dev:start
      SERVICE_0_CWD: .
      PROXY_WORKSPACE_ONLY: 'true'
    ports:
      - 4200:4200
    volumes:
      - .:/data:delegated
